[package]
name = "poly-commit"
version = "0.1.0"
authors = [
  "Alessandro Chiesa <alexch@berkeley.edu>",
  "Mary Maller <mary.maller.15@ucl.ac.uk>",
  "Yuncong Hu <huyuncongh@gmail.com>",
  "Pratyush Mishra <pratyush@berkeley.edu>",
  "Noah Vesely <noah.vesely.18@ucl.ac.uk>",
  "Nicholas Ward <npward@berkeley.edu>",
]
description = "A library for constructing polynomial commitment schemes for use in zkSNARKs"
repository = "https://github.com/scipr/poly-commit"
documentation = "https://docs.rs/poly-commit/"
keywords = ["cryptography", "polynomial commitments", "elliptic curves", "pairing"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
algebra = { git = "https://github.com/scipr-lab/zexe/", features = [ "parallel" ] }
ff-fft = { git = "https://github.com/scipr-lab/zexe/" }
bench-utils = { git = "https://github.com/scipr-lab/zexe/" }
rand = { version = "0.7" }
rayon = { version = "1" }
derivative = { version = "1" }

r1cs-core = { git = "https://github.com/scipr-lab/zexe", optional = true }
r1cs-std = { git = "https://github.com/scipr-lab/zexe", optional = true }

[profile.release]
opt-level = 3
lto = "thin"
incremental = true
debug = true

[profile.test]
opt-level = 3
debug-assertions = true
incremental = true
debug = true

[features]
print-trace = [ "bench-utils/print-trace" ]
r1cs = [ "r1cs-core", "r1cs-std" ]
